apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: controller
  newName: quay.io/fmatouschek/kubevirt-addon-manager
  newTag: latest
- name: manager
  newName: quay.io/0xFelix/kubevirt-addon-manager
  newTag: latest
