apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-addon-manager
roleRef:
  name: kubevirt-addon-manager
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: kubevirt-addon-manager
  kind: ServiceAccount
