apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-kubevirt-hyperconverged
  namespace: {{ .InstallNamespace }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: community-kubevirt-hyperconverged
  source: community-operators
  sourceNamespace: openshift-marketplace
